# Generated by Django 2.2.5 on 2023-09-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Star_Wars', '0002_auto_20230908_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='species',
        ),
        migrations.AlterField(
            model_name='character',
            name='side',
            field=models.CharField(choices=[('empire', 'Empire'), ('rebellion', 'Rebellion')], max_length=15),
        ),
    ]
