# Generated by Django 2.2.5 on 2023-09-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Star_Wars', '0003_auto_20230909_1628'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='character',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='side',
            field=models.CharField(choices=[('empire', 'Empire'), ('rebellion', 'Rebellion')], max_length=20),
        ),
    ]
